apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: todoapp
spec:
  containers:
  - name: busybox
    image: yauritux/busybox-curl
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
