apiVersion: v1
kind: Service
metadata:
  name: todoapp-clusterip-service
  namespace: mateapp
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
