apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-health
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health
            image: busyboxplus:curl
            command:
            - /bin/sh
            - -c 
            - curl http://todoapp-service.mateapp.svr.cluster.local/api/health
          restartPolicy: OnFailure

