apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-health-check
spec:
  schedule: "*/4 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health-check
            image: radial/busyboxplus:curl
            args:
            - /bin/sh
            - -c
            - curl http://todoapp.cluster.local/api/health
            resources:
              requests:
                memory: "64Mi"
                cpu: "400m"
              limits:
                memory: "128Mi"
                cpu: "800m"
          restartPolicy: OnFailure
      backoffLimit: 6
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Allow
