apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-health-check
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox-curl
              image: busyboxplus:curl
              command:
                - /bin/sh
                - -c
                - "curl http://todoapp-service.todoapp.svc.cluster.local/api/health"
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
          restartPolicy: OnFailure
