apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-cronjob
  namespace: todoapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busyboxplus:curl
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
            command:
            - /bin/sh
            - -c
            - curl http://todoapp-service.todoapp.svc.cluster.local:80/api/health
          restartPolicy: OnFailure
