apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"  # Every 4 minutes
  concurrencyPolicy: Allow
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todoapp
            image: ikulyk404/busyboxplus:curl
            resources:
              requests:
                memory: "100Mi"
                cpu: "100m"
              limits:
                memory: "200Mi"
                cpu: "200m"
          command: ["sh", "-c", "curl http://todoapp-service/api/health"]
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
