apiVersion: batch/v1
kind: CronJob
metadata:
  name: get-health-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: get-health
              image: radial/busyboxplus:curl
              resources:
                requests:
                  cpu: "100m"
                  memory: "64Mi"
                limits:
                  cpu: "200m"
                  memory: "128Mi"
              command:
                - /bin/sh
                - -c
                - curl todoapp-service.todoapp.svc.cluster.local/api/health
          restartPolicy: OnFailure
