apiVersion: batch/v1
kind: CronJob
metadata:
  name: healthcheck
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curlcontainer
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - curl http://todoapp-service.todoapp.svc.cluster.local/api/health
          restartPolicy: OnFailure
