apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-monitor
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busyboxplus:curl #
            resources: #
              requests:
                cpu: "100m"
                memory: "100Mi"
              limits:
                cpu: "200m"
                memory: "200Mi"
            command:
            - /bin/sh
            - -c
            - curl http://todoapp-service.todoapp.svc.cluster.local/api/health
          restartPolicy: OnFailure