apiVersion: batch/v1
kind: CronJob
metadata:
 name: cronjob
 namespace: mateapp
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
   spec:
     template:
       spec:
         containers:
         - name: todoapp
           image: radial/busyboxplus:curl
           resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
           command:
           - /bin/sh
           - -c
           - curl todoapp-nodeport.todoapp.svc.cluster.local/api/ready
         restartPolicy: OnFailure
