apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-cronjob
  namespace: todoapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: losiev/busyboxplus:curl
            command:
            - /bin/sh
            - -c
            - "curl http://todoapp-service.todoapp.svc.cluster.local/api/health"
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
          restartPolicy: OnFailure     
