apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: radial/busyboxplus:curl
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            command:
            - /bin/sh
            - -c
            - curl todoapp-nodeport.todoapp.svc.cluster.local/api/ready
          restartPolicy: OnFailure
