apiVersion: batch/v1
kind: CronJob
metadata:
 name: todoapp-cronjob
 namespace: mateapp
spec:
 schedule: "*/1 * * * *"
 concurrencyPolicy: Allow
 startingDeadlineSeconds: 100
 successfulJobsHistoryLimit: 10
 failedJobsHistoryLimit: 5
 jobTemplate:
   spec:
     template:
       spec:
         containers:
         - name: cronjob-container
           image: parthyadav/busyboxplus:curl-v22.12.17
           resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
           command: ["/bin/sh", "-c"]
           args: 
            - "curl -X GET http://todoapp-clusterip-service.mateapp.svc.cluster.local:80/api/alive"
         restartPolicy: OnFailure
