apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 19
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: radial/busyboxplus:curl
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"
            args:
              - /bin/sh
              - -c
              - curl http://todoapp-service.todoapp.svc.cluster.local/api/health
          restartPolicy: OnFailure
