apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-health-check
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: health-checker
            image: busyboxplus:curl
            command: ["/bin/sh", "-c"]
            args:
              - "curl http://todoapp-service.mateapp.svc.cluster.local/api/health"
            resources:
              requests:
                cpu: "100m"
                memory: "100Mi"
              limits:
                cpu: "200m"
                memory: "200Mi"
          restartPolicy: OnFailure
