apiVersion: batch/v1
kind: CronJob
metadata:
  name: todoapp-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todoapp-cronjob
            image: radial/busyboxplus:curl
            command:
            - /bin/sh
            - -c
            - curl http://todoapp-nodeport.mateapp.svc.cluster.local/api/ready
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          restartPolicy: OnFailure
