apiVersion: batch/v1
kind: CronJob
metadata:
 name: todoapp-cronjob
 namespace: mateapp
spec:
 schedule: "*/4 * * * *"
 concurrencyPolicy: Allow
 startingDeadlineSeconds: 100
 successfulJobsHistoryLimit: 10
 failedJobsHistoryLimit: 5
 jobTemplate:
   spec:
     template:
       spec:
         containers:
         - name: busybox
           image: curlimages/curl
           command:
           - /bin/sh
           - -c
           - curl http://todoappclusterip.todoapp.svc.cluster.local/api/health
           resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
         restartPolicy: OnFailure
