apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
  namespace: todoapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: curlimages/curl:latest
              command: ["/bin/sh", "-c", "curl -f http://todoapp.todoapp.svc.cluster.local/api/health || exit 1"]
          restartPolicy: OnFailure
