apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todoapp
            image: curlimages/curl
            command:
            - /bin/sh
            - -c
            - curl http://todoapp-service.todoapp.svc.cluster.local/api/ready
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
          restartPolicy: OnFailure
