apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todo-monitor
  namespace: mateapp
  labels:
    app: todo-monitor
spec:
  selector:
    matchLabels:
      app: todo-monitor
  template:
    metadata:
      labels:
        app: todo-monitor
    spec:
      containers:
      - name: todo-monitor
        image: busyboxplus:curl
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        command:
        - /bin/sh
        - -c
        - curl http://todoapp-service.todoapp.svc.cluster.local && sleep 5