apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp-daemonset
  namespace: mateapp
  labels:
    app: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: busybox-container
        image: parthyadav/busyboxplus:curl-v22.12.17
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        ports:
        - containerPort: 80
          hostPort: 30008
        command: ["/bin/sh"]
        args: ["-c", "while true; do curl -s http://todoapp-clusterip-service.mateapp.svc.cluster.local:80; sleep 5; done"]
