apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
  namespace: mateapp
  labels:
    app: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: busyboxplus:curl
          command: ["/bin/sh", "-c", "while sleep 5; do curl http://todoapp-service.mateapp.svc.cluster.local; done"]
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          ports:
            - containerPort: 80
              hostPort: 30008
