apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonsetcurl
  namespace: mateapp
  labels:
    app: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: curlcontainer
          image: curlimages/curl:latest
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          command:
          - /bin/sh
          - -c
          - |
            while true; do
              curl http://todoapp-service.todoapp.svc.cluster.local/;
              sleep 5;
            done
