apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp-daemon
  namespace: todoapp
  labels:
    app: todoapp-daemon
spec:
  selector:
    matchLabels:
      app: todoapp-daemon
  template:
    metadata:
      labels:
        app: todoapp-daemon
    spec:
      containers:
        - name: todoapp-daemon
          image: curlimages/curl:latest
          command:
            ["sh", "-c", "watch -n 5 curl http://todoapp.todoapp.svc.cluster.local"]
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          ports:
          - containerPort: 80
            hostPort: 30008
