apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp-daemonset
  namespace: todoapp
spec:
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: radial/busyboxplus:curl
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "250m"
        args:
        - /bin/sh
        - -c
        - |
          while true; do
            curl http://todoapp-clusterip/api/health;
            sleep 5;
          done
