apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp
  namespace: mateapp
  labels:
    app: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: ikulyk404/busyboxplus:curl
        resources:
          requests:
            cpu: "100m"
            memory: "75Mi"
          limits:
            cpu: "200m"
            memory: "150Mi"
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            curl http://todoapp-service;
            sleep 5;
          done
        ports:
        - containerPort: 80
          hostPort: 30008
