apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-daemonset
  namespace: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: busybox
        image: busyboxplus:curl
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        command:
        - sh
        - -c
        - |
          while sleep 5; do curl http://todoapp-daemon.mateapp.svc.cluster.local; done
        ports:
        - containerPort: 80
