apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp-daemonset
  namespace: todoapp
  labels:
    app: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp-daemonset
          image: ikulyk404/busyboxplus:curl
          command: ["sh", "-c", "while true; do curl http://todoapp-service.todoapp.svc.cluster.local; sleep 5; done"]
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          ports:
          - containerPort: 80
            hostPort: 30008
