apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: busybox-daemonset
  namespace: todoapp
spec:
  selector:
    matchLabels:
      app: busybox-daemonset
  template:
    metadata:
      labels:
        app: busybox-daemonset
    spec:
      containers:
      - name: busybox
        image: curlimages/curl:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        command: ["/bin/sh"]
        args:
        - -c
        - "while true; do curl http://todoapp-service.mateapp.svc.cluster.local; sleep 5; done"
