apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp-deamonset
  namespace: mateapp
  labels:
    app: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
        - name: curl
          image: alpine:latest
          command:
          - sh
          - -c
          - |
            apk add --no-cache curl;
            while true; do
              curl http://todoapp-service.todoapp.svc.cluster.local/;
              sleep 5;
            done
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "200m"
              memory: "200Mi"
          ports:
            - containerPort: 80
              hostPort: 30008
