apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: todoapp-daemonset
  namespace: mateapp
spec:
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: busybox
        image: radial/busyboxplus:curl
        command: ["/bin/sh", "-c", "while sleep 5; do curl todoapp-service.mateapp.svc.cluster.local; done"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "150m"
        ports:
        - containerPort: 80
          hostPort: 30008